aluno = (input('Digite o nome do aluno:'))
print('=' * 50)
print(f'O nome digitado foi {aluno}')
print('=' * 50)
at1 = float(input('\nDigite a nota da sua primeira atividade:'))
print('=' * 50)
at2 = float(input('\nDigite a nota da sua segunda atividade:'))
print('=' * 50)
at3 = float(input('\nDigite a nota da sua terceira atividade:'))
print('=' * 50)
at4 = float(input('\nDigite a nota da sua quarta atividade:'))
print('=' * 50)
at5 = float(input('\nDigite a nota da sua quinta atividade:'))
print('=' * 50)
total = float(at1+at2+at3+at4+at5)
print(f'\nA soma das suas notas é {total}')
media = float(total/5)
print(f'A media das suas notas é {media}')
coef = float(media * 0.06)
print(f'A soma final das atividades foi {coef}')
print('=' * 50)
siva = float(input('\nDigite a nota do seu SIVA:'))
final = float(coef+siva)
print('Processando...')
print('=' * 50)
print(f'A sua media final foi {final}')
print('Codigo feito por João Vitor Do Nascimento 2 Info C')
 